const cats=[["🕳️","Bache"],["💡","Alumbrado"],["🚦","Señalización"],["🗑️","Limpieza"],["🪑","Mobiliario urbano"],["💧","Agua / alcantarillado"],["•••","Otro"]];let state={step:1,category:"",lat:null,lng:null,address:"",photoFile:null},all=[],marker;const map=L.map("report-map").setView([40.4168,-3.7038],14);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"&copy; OpenStreetMap contributors"}).addTo(map);Backend.incidents().then(x=>all=x);
categories.innerHTML=cats.map(([ico,n])=>`<button class="category-option" data-cat="${n}"><span>${ico}</span><b>${n}</b></button>`).join("");document.querySelectorAll(".category-option").forEach(b=>b.onclick=()=>{document.querySelectorAll(".category-option").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.category=b.dataset.cat;document.querySelector('[data-step="1"] .next').disabled=false});
document.querySelectorAll(".next").forEach(b=>b.onclick=()=>go(state.step+1));document.querySelectorAll(".back").forEach(b=>b.onclick=()=>go(Math.max(1,state.step-1)));
function go(n){state.step=n;document.querySelectorAll(".wizard-step").forEach(x=>x.classList.toggle("active",+x.dataset.step===n));step_label.textContent=n<=4?`Paso ${n} de 4`:"Completado";progress.style.width=`${Math.min(n,4)*25}%`;if(n===2)setTimeout(()=>map.invalidateSize(),80);if(n===3)findDuplicates();scrollTo({top:0,behavior:"smooth"})}
locate.onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(p=>setPoint(p.coords.latitude,p.coords.longitude),()=>{address.textContent="No pudimos obtener tu ubicación. Toca el punto en el mapa."},{enableHighAccuracy:true}):address.textContent="Geolocalización no disponible. Toca el mapa.";map.on("click",e=>setPoint(e.latlng.lat,e.latlng.lng));
async function setPoint(a,b){state.lat=a;state.lng=b;if(marker)marker.setLatLng([a,b]);else marker=L.marker([a,b],{draggable:true}).addTo(map);marker.off("dragend").on("dragend",()=>{let p=marker.getLatLng();setPoint(p.lat,p.lng)});map.setView([a,b],17);coords.textContent=`${a.toFixed(5)}, ${b.toFixed(5)}`;address.textContent="Buscando dirección…";document.querySelector('[data-step="2"] .next').disabled=false;try{let r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${a}&lon=${b}&zoom=18&addressdetails=1`,{headers:{"Accept-Language":"es"}}),j=await r.json(),ad=j.address||{};state.address=[ad.road||ad.pedestrian||ad.footway,ad.house_number].filter(Boolean).join(" ")||j.display_name?.split(",").slice(0,2).join(", ")||"Ubicación seleccionada";address.textContent=state.address}catch{state.address="Ubicación seleccionada";address.textContent=state.address}}
function findDuplicates(){let near=all.filter(i=>!["Resuelta","Descartada","Duplicada"].includes(i.status)).map(i=>({...i,d:App.dist(state.lat,state.lng,i.lat,i.lng),match:i.category===state.category})).filter(i=>i.d<=150&&(i.match||i.d<=60)).sort((a,b)=>(b.match-a.match)||(a.d-b.d)).slice(0,3);duplicate_title.textContent=near.length?"¿Ya está reportado?":"No hemos encontrado un aviso igual";duplicate_results.innerHTML=near.length?near.map(i=>`<article class="dup-v9">${i.photo?`<img src="${i.photo}" alt="">`:`<div class="dup-placeholder">📍</div>`}<div><h3>${App.esc(i.category)}</h3><p>${App.esc(i.description)}</p><p><strong>A ${Math.round(i.d)} m</strong> · 👥 ${i.votes} confirmaciones · ${App.esc(i.status)}</p><button class="btn primary" onclick="confirmExisting('${i.id}')">Sí, es este · Yo también lo he visto</button></div></article>`).join(""):`<div class="notice">Puedes continuar y crear un nuevo aviso.</div>`}
async function confirmExisting(id){try{await Backend.vote(id);let i=await Backend.incident(id);state.step=5;document.querySelectorAll(".wizard-step").forEach(x=>x.classList.toggle("active",+x.dataset.step===5));step_label.textContent="Completado";progress.style.width="100%";await Backend.follow(id,true);success_card.innerHTML=`<strong>Has confirmado una incidencia existente</strong><p>${App.esc(i.category)} · ${App.esc(i.description)}</p><p>👥 Ahora tiene ${i.votes} confirmaciones.</p>`;view_created.href=`incidencia.html?id=${id}`}catch(e){alert(e.message)}}
new_report.onclick=()=>go(4);photo.onchange=e=>{state.photoFile=e.target.files[0]||null;if(state.photoFile){let u=URL.createObjectURL(state.photoFile);preview.innerHTML=`<img class="photo" src="${u}" alt="Vista previa de la foto">`}};description.oninput=()=>chars.textContent=description.value.length;
submit_report.onclick=async()=>{let desc=description.value.trim();if(desc.length<3){form_feedback.textContent="⚠ Describe brevemente el problema (mínimo 3 caracteres).";description.focus();return}let risk=+document.querySelector('input[name="risk"]:checked').value,btn=submit_report;btn.disabled=true;btn.textContent="Enviando…";form_feedback.textContent=state.photoFile?"Comprimiendo foto y enviando…":"Enviando aviso…";try{let i=await Backend.createIncident({category:state.category,description:desc,lat:state.lat,lng:state.lng,urgency:risk,photoFile:state.photoFile,address:state.address});await Backend.follow(i.id,true);success_card.innerHTML=`<strong>Incidencia #${App.esc(String(i.id))}</strong><p>${App.esc(state.category)} · ${App.esc(state.address)}</p><p>👥 Eres la primera persona que la confirma.</p>`;view_created.href=`incidencia.html?id=${i.id}`;go(5)}catch(e){form_feedback.textContent="⚠ "+e.message;btn.disabled=false;btn.textContent="Enviar aviso"}};
